# Config file for github pull request labeler
# https://github.com/actions/labeler
root-project:
  - ./*
github-config:
  - ./.github/*
github-workflows:
  - ./.github/workflows/*
maven:
  - ./pom.xml
  - ./**/pom.xml
deploy-debug-project:
  - ./deploy-debug/*
  - ./deploy-debug/**/*
term-project:
  - ./term/*
  - ./term/**/*
services-project:
  - ./services/*
  - ./services/**/*
interface-project:
  - ./interface/*
  - ./interface/**/*
grammar-project:
  - ./grammar/*
  - ./grammar/**/*
docker-project:
  - ./test-deploy-docker/*
  - ./test-deploy-docker/**/*
java-source:
  - ./*.java
  - ./**/*.java
test:
  - ./*test*
  - ./**/*test*
  - ./*Test*
  - ./**/*Test*
junit:
  - ./term/src/test/*.java
  - ./term/src/test/**/*.java
  - ./services/src/test/*.java
  - ./services/src/test/**/*.java
grammar:
  - ./grammar/*.g4
  - ./grammar/**/*.g4
interface:
  - ./interface/*.yaml
  - ./interface/**/*.yaml