name: "Test correct deployment"
on:
    [push]
jobs:
  build:
    name: build_deploy_docker
    runs-on: ubuntu-latest        
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Extract branch name 
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"     
    - name: Build docker image
      id: docker_build
      run: docker build --no-cache --build-arg branch=${{ steps.extract_branch.outputs.branch }} -t mathparser-docker:test ./test-deploy-docker/
    - name: Run container
      id: run_docker
      run: docker run --cidfile container_id -p 8080:8080 mathparser-docker:test java -version
    - name: Show container id
      run: cat container_id
