name: "Test correct deployment"
on:
    [push]
jobs:
  build:
    name: build_deploy_docker
    runs-on: ubuntu-latest        
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Extract branch name 
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"     
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./test-deploy-docker/
          file: ./test-deploy-docker/Dockerfile
          push: false
          tags: mathparser-docker:test
          build-args: branch=${{ steps.extract_branch.outputs.branch }}
          no-cache: true
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
