name: "Test correct deployment"
on:
    [push]
jobs:
  build:
    name: build_deploy_docker
    runs-on: ubuntu-latest        
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Extract branch name 
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"     
    - name: Build docker image
      id: docker_build
      run: docker build --no-cache --build-arg branch=${{ steps.extract_branch.outputs.branch }} -t mathparser-docker:test ./test-deploy-docker/
    - name: Run container
      id: run_docker
      run: docker run --name mathparser -p 8080:8080 --rm -d mathparser-docker:test
    - name: Test correct deployment using the /test/ping request
      run: ./test-deploy-docker/test-mathparser-request.sh
    - name: Stop container
      run: docker stop mathparser
