name: "Test if JUnit tests are executed"
on:
    [push]
jobs:
  build:
    name: test_tests
    runs-on: ubuntu-latest        
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4    
    - name: Make test folder
      run: mkdir test
    - name: Create test file
      run: touch ./test/JUnitTestExecutionTestfile
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Test with Maven
      run: mvn clean test --file ./pom.xml    
    - name: Check if new file exist
      shell: bash
      run: [ -f ./test/JUnitTestExecutionTestfile.new ]
    - name: Remove folder and files
      run: rm -rf ./test
