name: "Test correct deployment"
on:
    [push, pull_request]
jobs:
  build:
    name: build_deploy_docker
    runs-on: ubuntu-latest        
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true clean install --file ./pom.xml
    - name: Copy file
      shell: bash
      run: cp ./deploy-debug/target/MathParserDev.war ./test-deploy-docker/
    - name: Build docker image
      id: docker_build
      run: docker build --no-cache -t mathparser-docker:test ./test-deploy-docker/
    - name: Run container
      id: run_docker
      run: docker run --name mathparser -p 127.0.0.1:8080:8080 --rm -d mathparser-docker:test
    - name: Test correct deployment using the /test/ping request
      run: ./test-deploy-docker/test-mathparser-request.sh
    - name: Stop container
      run: docker stop mathparser
